import { formatDate, getFontSize, getSpacing } from './templateUtils';
const T = ({ data, theme }) => {const pi=data?.personalInfo||{};const font=theme?.fontFamily||'Times New Roman';const fs=getFontSize(theme?.fontSize);const sp=getSpacing(theme?.spacing);return(<div style={{fontFamily:font,color:'#000',padding:sp.padding,background:'white',minHeight:'1056px',lineHeight:1.4}}>
<div style={{textAlign:'center',marginBottom:'16px'}}><h1 style={{fontSize:'22px',fontWeight:700,margin:0,textTransform:'uppercase'}}>{pi.fullName||'Your Name'}</h1><div style={{fontSize:'11px',color:'#333',marginTop:'4px'}}>{[pi.email,pi.phone,pi.location,pi.linkedin].filter(Boolean).join(' | ')}</div></div>
<hr style={{border:'none',borderTop:'2px solid #000',margin:'0 0 12px'}}/>
{pi.summary&&<div style={{marginBottom:'14px'}}><h2 style={{fontSize:'13px',fontWeight:700,textTransform:'uppercase',borderBottom:'1px solid #000',paddingBottom:'2px',marginBottom:'6px'}}>Professional Summary</h2><p style={{fontSize:fs.body,margin:0}}>{pi.summary}</p></div>}
{data?.experience?.length>0&&<div style={{marginBottom:'14px'}}><h2 style={{fontSize:'13px',fontWeight:700,textTransform:'uppercase',borderBottom:'1px solid #000',paddingBottom:'2px',marginBottom:'6px'}}>Experience</h2>{data.experience.map((e,i)=>(<div key={i} style={{marginBottom:'10px'}}><div style={{display:'flex',justifyContent:'space-between'}}><strong style={{fontSize:fs.title}}>{e.position}, {e.company}</strong><span style={{fontSize:fs.body}}>{formatDate(e.startDate)} – {e.current?'Present':formatDate(e.endDate)}</span></div>{e.bullets?.filter(b=>b).length>0&&<ul style={{margin:'4px 0 0 18px',padding:0}}>{e.bullets.filter(b=>b).map((b,bi)=>(<li key={bi} style={{fontSize:fs.body,marginBottom:'2px'}}>{b}</li>))}</ul>}</div>))}</div>}
{data?.education?.length>0&&<div style={{marginBottom:'14px'}}><h2 style={{fontSize:'13px',fontWeight:700,textTransform:'uppercase',borderBottom:'1px solid #000',paddingBottom:'2px',marginBottom:'6px'}}>Education</h2>{data.education.map((e,i)=>(<div key={i} style={{marginBottom:'6px'}}><div style={{display:'flex',justifyContent:'space-between'}}><strong style={{fontSize:fs.title}}>{e.degree} {e.field&&`in ${e.field}`}, {e.institution}</strong><span style={{fontSize:fs.body}}>{formatDate(e.startDate)} – {formatDate(e.endDate)}</span></div>{e.gpa&&<div style={{fontSize:fs.body}}>GPA: {e.gpa}</div>}</div>))}</div>}
{data?.skills?.length>0&&<div style={{marginBottom:'14px'}}><h2 style={{fontSize:'13px',fontWeight:700,textTransform:'uppercase',borderBottom:'1px solid #000',paddingBottom:'2px',marginBottom:'6px'}}>Skills</h2><p style={{fontSize:fs.body,margin:0}}>{data.skills.map(s=>s.name).join(', ')}</p></div>}
{data?.projects?.length>0&&<div style={{marginBottom:'14px'}}><h2 style={{fontSize:'13px',fontWeight:700,textTransform:'uppercase',borderBottom:'1px solid #000',paddingBottom:'2px',marginBottom:'6px'}}>Projects</h2>{data.projects.map((p,i)=>(<div key={i} style={{marginBottom:'6px'}}><strong style={{fontSize:fs.title}}>{p.name}</strong>{p.technologies&&<span style={{fontSize:fs.body}}> ({p.technologies})</span>}{p.description&&<p style={{fontSize:fs.body,margin:'2px 0'}}>{p.description}</p>}</div>))}</div>}
{data?.certifications?.length>0&&<div><h2 style={{fontSize:'13px',fontWeight:700,textTransform:'uppercase',borderBottom:'1px solid #000',paddingBottom:'2px',marginBottom:'6px'}}>Certifications</h2>{data.certifications.map((c,i)=>(<div key={i} style={{fontSize:fs.body,marginBottom:'2px'}}>{c.name} – {c.issuer}{c.date&&`, ${formatDate(c.date)}`}</div>))}</div>}
</div>)};
export default T;
