import { formatDate, getFontSize, getSpacing } from './templateUtils';
const T = ({ data, theme }) => {const pi=data?.personalInfo||{};const font=theme?.fontFamily||'Roboto';const fs=getFontSize(theme?.fontSize);const sp=getSpacing(theme?.spacing);return(<div style={{fontFamily:font,color:'#222',padding:sp.padding,background:'white',minHeight:'1056px',lineHeight:1.5}}>
<div style={{textAlign:'center',marginBottom:'14px',paddingBottom:'10px',borderBottom:'1px solid #ddd'}}><h1 style={{fontSize:'22px',fontWeight:500,margin:0,letterSpacing:'1px'}}>{pi.fullName||'Your Name'}</h1><div style={{fontSize:'11px',color:'#666',marginTop:'6px'}}>{[pi.email,pi.phone,pi.location,pi.linkedin].filter(Boolean).join('  ·  ')}</div></div>
{pi.summary&&<div style={{marginBottom:'14px'}}><h2 style={{fontSize:'11px',fontWeight:600,color:'#444',textTransform:'uppercase',letterSpacing:'1px',marginBottom:'6px',paddingBottom:'3px',borderBottom:'1px solid #eee'}}>Professional Profile</h2><p style={{fontSize:fs.body,margin:0,color:'#333'}}>{pi.summary}</p></div>}
{data?.experience?.length>0&&<div style={{marginBottom:'14px'}}><h2 style={{fontSize:'11px',fontWeight:600,color:'#444',textTransform:'uppercase',letterSpacing:'1px',marginBottom:'6px',paddingBottom:'3px',borderBottom:'1px solid #eee'}}>Experience</h2>{data.experience.map((e,i)=>(<div key={i} style={{marginBottom:'10px'}}><div style={{display:'flex',justifyContent:'space-between'}}><div><strong style={{fontSize:fs.title,color:'#111'}}>{e.position}</strong><span style={{color:'#666'}}> | {e.company}</span></div><span style={{fontSize:'10px',color:'#999'}}>{formatDate(e.startDate)} – {e.current?'Present':formatDate(e.endDate)}</span></div>{e.bullets?.filter(b=>b).length>0&&<ul style={{margin:'4px 0 0 16px',padding:0}}>{e.bullets.filter(b=>b).map((b,bi)=>(<li key={bi} style={{fontSize:fs.body,marginBottom:'2px',color:'#333'}}>{b}</li>))}</ul>}</div>))}</div>}
{data?.education?.length>0&&<div style={{marginBottom:'14px'}}><h2 style={{fontSize:'11px',fontWeight:600,color:'#444',textTransform:'uppercase',letterSpacing:'1px',marginBottom:'6px',paddingBottom:'3px',borderBottom:'1px solid #eee'}}>Education</h2>{data.education.map((e,i)=>(<div key={i} style={{marginBottom:'6px',display:'flex',justifyContent:'space-between'}}><div><strong style={{fontSize:fs.title}}>{e.degree} {e.field&&`in ${e.field}`}</strong><span style={{color:'#666'}}> — {e.institution}</span>{e.gpa&&<span style={{color:'#999'}}> | GPA: {e.gpa}</span>}</div><span style={{fontSize:'10px',color:'#999'}}>{formatDate(e.endDate)}</span></div>))}</div>}
{data?.skills?.length>0&&<div style={{marginBottom:'14px'}}><h2 style={{fontSize:'11px',fontWeight:600,color:'#444',textTransform:'uppercase',letterSpacing:'1px',marginBottom:'6px',paddingBottom:'3px',borderBottom:'1px solid #eee'}}>Technical Skills</h2><p style={{fontSize:fs.body,margin:0}}>{data.skills.map(s=>s.name).join(', ')}</p></div>}
{data?.projects?.length>0&&<div style={{marginBottom:'14px'}}><h2 style={{fontSize:'11px',fontWeight:600,color:'#444',textTransform:'uppercase',letterSpacing:'1px',marginBottom:'6px',paddingBottom:'3px',borderBottom:'1px solid #eee'}}>Projects</h2>{data.projects.map((p,i)=>(<div key={i} style={{marginBottom:'6px'}}><strong style={{fontSize:fs.title}}>{p.name}</strong>{p.technologies&&<span style={{color:'#999'}}> ({p.technologies})</span>}{p.description&&<div style={{fontSize:fs.body,color:'#333'}}>{p.description}</div>}</div>))}</div>}
{data?.certifications?.length>0&&<div><h2 style={{fontSize:'11px',fontWeight:600,color:'#444',textTransform:'uppercase',letterSpacing:'1px',marginBottom:'6px',paddingBottom:'3px',borderBottom:'1px solid #eee'}}>Certifications</h2>{data.certifications.map((c,i)=>(<div key={i} style={{fontSize:fs.body,marginBottom:'2px'}}>{c.name} — {c.issuer}{c.date&&` (${formatDate(c.date)})`}</div>))}</div>}
</div>)};
export default T;
