import { formatDate, getFontSize, getSpacing } from './templateUtils';
const T = ({ data, theme }) => {
  const pi = data?.personalInfo || {};const color = theme?.primaryColor || '#f59e0b';const font = theme?.fontFamily || 'Poppins';const fs = getFontSize(theme?.fontSize);const sp = getSpacing(theme?.spacing);
  const colors = ['#f59e0b', '#ef4444', '#8b5cf6', '#06b6d4', '#10b981'];
  return (<div style={{ fontFamily: font, color: '#1f2937', padding: sp.padding, background: 'white', minHeight: '1056px' }}>
    <div style={{ background: `linear-gradient(135deg, ${colors[0]}20, ${colors[1]}20, ${colors[2]}20)`, padding: '24px', borderRadius: '16px', marginBottom: sp.section }}>
      <h1 style={{ fontSize: fs.name, fontWeight: 800, background: `linear-gradient(135deg, ${colors[0]}, ${colors[1]}, ${colors[2]})`, WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', margin: 0 }}>{pi.fullName || 'Your Name'}</h1>
      <div style={{ fontSize: fs.body, color: '#6b7280', marginTop: '8px', display: 'flex', flexWrap: 'wrap', gap: '10px' }}>{pi.email && <span>✉ {pi.email}</span>}{pi.phone && <span>📱 {pi.phone}</span>}{pi.location && <span>📍 {pi.location}</span>}</div>
      {pi.summary && <p style={{ fontSize: fs.body, color: '#374151', marginTop: '10px', lineHeight: 1.6 }}>{pi.summary}</p>}
    </div>
    {data?.experience?.length > 0 && <div style={{ marginBottom: sp.section }}><h2 style={{ fontSize: fs.section, fontWeight: 700, color: colors[0], marginBottom: sp.item, display: 'flex', alignItems: 'center', gap: '8px' }}>💼 Experience</h2>{data.experience.map((exp, i) => (<div key={i} style={{ marginBottom: '14px', padding: '12px', borderLeft: `4px solid ${colors[i % colors.length]}`, background: `${colors[i % colors.length]}08`, borderRadius: '0 8px 8px 0' }}><div style={{ display: 'flex', justifyContent: 'space-between' }}><strong style={{ fontSize: fs.title }}>{exp.position}</strong><span style={{ fontSize: '10px', color: '#9ca3af' }}>{formatDate(exp.startDate)} – {exp.current ? 'Present' : formatDate(exp.endDate)}</span></div><div style={{ fontSize: fs.body, color: colors[i % colors.length], fontWeight: 500 }}>{exp.company}</div>{exp.bullets?.filter(b => b).map((b, bi) => (<p key={bi} style={{ fontSize: fs.body, margin: '3px 0', color: '#4b5563' }}>• {b}</p>))}</div>))}</div>}
    {data?.education?.length > 0 && <div style={{ marginBottom: sp.section }}><h2 style={{ fontSize: fs.section, fontWeight: 700, color: colors[1], marginBottom: sp.item }}>🎓 Education</h2>{data.education.map((edu, i) => (<div key={i} style={{ marginBottom: sp.item }}><strong style={{ fontSize: fs.title }}>{edu.degree} {edu.field && `in ${edu.field}`}</strong><div style={{ fontSize: fs.body, color: colors[1] }}>{edu.institution}{edu.gpa && ` • GPA: ${edu.gpa}`}</div></div>))}</div>}
    {data?.skills?.length > 0 && <div style={{ marginBottom: sp.section }}><h2 style={{ fontSize: fs.section, fontWeight: 700, color: colors[2], marginBottom: sp.item }}>⚡ Skills</h2><div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px' }}>{data.skills.map((s, i) => (<span key={i} style={{ fontSize: '11px', padding: '5px 14px', borderRadius: '20px', background: `${colors[i % colors.length]}15`, color: colors[i % colors.length], fontWeight: 600 }}>{s.name}</span>))}</div></div>}
    {data?.projects?.length > 0 && <div style={{ marginBottom: sp.section }}><h2 style={{ fontSize: fs.section, fontWeight: 700, color: colors[3], marginBottom: sp.item }}>🚀 Projects</h2>{data.projects.map((p, i) => (<div key={i} style={{ marginBottom: sp.item }}><strong style={{ fontSize: fs.title }}>{p.name}</strong>{p.technologies && <span style={{ fontSize: fs.body, color: '#9ca3af' }}> | {p.technologies}</span>}{p.description && <p style={{ fontSize: fs.body, margin: '2px 0' }}>{p.description}</p>}</div>))}</div>}
    {data?.certifications?.length > 0 && <div><h2 style={{ fontSize: fs.section, fontWeight: 700, color: colors[4], marginBottom: sp.item }}>📜 Certifications</h2>{data.certifications.map((c, i) => (<div key={i} style={{ fontSize: fs.body, marginBottom: '3px' }}><strong>{c.name}</strong> – {c.issuer}</div>))}</div>}
  </div>);
};
export default T;
