import { formatDate, getFontSize, getSpacing } from './templateUtils';
const T = ({ data, theme }) => {const pi=data?.personalInfo||{};const color=theme?.primaryColor||'#e11d48';const font=theme?.fontFamily||'Outfit';const fs=getFontSize(theme?.fontSize);const sp=getSpacing(theme?.spacing);return(<div style={{fontFamily:font,color:'#1f2937',minHeight:'1056px',background:'white'}}>
<div style={{background:`linear-gradient(135deg,${color}10,${color}05)`,padding:'32px',position:'relative',overflow:'hidden'}}><div style={{position:'absolute',top:'-30px',right:'-30px',width:'120px',height:'120px',borderRadius:'50%',background:`${color}10`}}/><div style={{position:'absolute',bottom:'-20px',right:'40px',width:'60px',height:'60px',borderRadius:'50%',background:`${color}08`}}/><h1 style={{fontSize:'30px',fontWeight:900,margin:0,position:'relative'}}>{pi.fullName||'Your Name'}</h1><div style={{fontSize:fs.body,color:'#6b7280',marginTop:'8px',display:'flex',flexWrap:'wrap',gap:'8px',position:'relative'}}>{pi.email&&<span style={{background:'white',padding:'2px 10px',borderRadius:'20px',fontSize:'10px'}}>{pi.email}</span>}{pi.phone&&<span style={{background:'white',padding:'2px 10px',borderRadius:'20px',fontSize:'10px'}}>{pi.phone}</span>}{pi.location&&<span style={{background:'white',padding:'2px 10px',borderRadius:'20px',fontSize:'10px'}}>{pi.location}</span>}</div>{pi.summary&&<p style={{fontSize:fs.body,color:'#374151',marginTop:'14px',lineHeight:1.7,position:'relative'}}>{pi.summary}</p>}</div>
<div style={{padding:sp.padding}}>
{data?.experience?.length>0&&<div style={{marginBottom:sp.section}}><h2 style={{fontSize:fs.section,fontWeight:800,color,marginBottom:sp.item,display:'inline-block',borderBottom:`3px solid ${color}`}}>Experience</h2>{data.experience.map((e,i)=>(<div key={i} style={{marginBottom:'16px'}}><div style={{display:'flex',justifyContent:'space-between'}}><div><strong style={{fontSize:fs.title}}>{e.position}</strong><span style={{fontSize:fs.body,color:color,fontWeight:500}}> · {e.company}</span></div><span style={{fontSize:'10px',color:'#9ca3af'}}>{formatDate(e.startDate)}–{e.current?'Present':formatDate(e.endDate)}</span></div>{e.bullets?.filter(b=>b).map((b,bi)=>(<p key={bi} style={{fontSize:fs.body,margin:'3px 0 3px 10px',color:'#4b5563'}}>◆ {b}</p>))}</div>))}</div>}
{data?.education?.length>0&&<div style={{marginBottom:sp.section}}><h2 style={{fontSize:fs.section,fontWeight:800,color,marginBottom:sp.item,display:'inline-block',borderBottom:`3px solid ${color}`}}>Education</h2>{data.education.map((e,i)=>(<div key={i} style={{marginBottom:sp.item}}><strong style={{fontSize:fs.title}}>{e.degree} {e.field&&`in ${e.field}`}</strong><div style={{fontSize:fs.body,color:'#6b7280'}}>{e.institution}{e.gpa&&` • GPA: ${e.gpa}`}</div></div>))}</div>}
{data?.skills?.length>0&&<div style={{marginBottom:sp.section}}><h2 style={{fontSize:fs.section,fontWeight:800,color,marginBottom:sp.item,display:'inline-block',borderBottom:`3px solid ${color}`}}>Skills</h2><div style={{display:'flex',flexWrap:'wrap',gap:'5px'}}>{data.skills.map((s,i)=>(<span key={i} style={{fontSize:'10px',padding:'4px 12px',background:i%2===0?`${color}10`:'#f3f4f6',color:i%2===0?color:'#374151',borderRadius:'6px',fontWeight:500}}>{s.name}</span>))}</div></div>}
{data?.projects?.length>0&&<div style={{marginBottom:sp.section}}><h2 style={{fontSize:fs.section,fontWeight:800,color,marginBottom:sp.item,display:'inline-block',borderBottom:`3px solid ${color}`}}>Projects</h2>{data.projects.map((p,i)=>(<div key={i} style={{marginBottom:sp.item}}><strong style={{fontSize:fs.title}}>{p.name}</strong>{p.technologies&&<span style={{fontSize:fs.body,color:'#9ca3af'}}> | {p.technologies}</span>}{p.description&&<p style={{fontSize:fs.body,margin:'2px 0'}}>{p.description}</p>}</div>))}</div>}
{data?.certifications?.length>0&&<div><h2 style={{fontSize:fs.section,fontWeight:800,color,marginBottom:sp.item,display:'inline-block',borderBottom:`3px solid ${color}`}}>Certifications</h2>{data.certifications.map((c,i)=>(<div key={i} style={{fontSize:fs.body,marginBottom:'3px'}}><strong>{c.name}</strong> – {c.issuer}</div>))}</div>}
</div></div>)};
export default T;
