import { formatDate, getFontSize, getSpacing } from './templateUtils';
const T = ({ data, theme }) => {const pi=data?.personalInfo||{};const color=theme?.primaryColor||'#14b8a6';const font=theme?.fontFamily||'Inter';const fs=getFontSize(theme?.fontSize);const sp=getSpacing(theme?.spacing);return(<div style={{fontFamily:font,color:'#1f2937',padding:sp.padding,background:'white',minHeight:'1056px'}}>
<div style={{marginBottom:sp.section,position:'relative'}}><div style={{position:'absolute',top:0,left:0,width:'60px',height:'60px',borderRadius:'50%',background:`${color}15`,zIndex:0}}/><div style={{position:'relative',zIndex:1}}><h1 style={{fontSize:fs.name,fontWeight:800,margin:0}}>{pi.fullName||'Your Name'}</h1><div style={{width:'40px',height:'4px',background:color,borderRadius:'2px',margin:'8px 0'}}/><div style={{fontSize:fs.body,color:'#6b7280',display:'flex',flexWrap:'wrap',gap:'10px'}}>{pi.email&&<span>{pi.email}</span>}{pi.phone&&<span>| {pi.phone}</span>}{pi.location&&<span>| {pi.location}</span>}{pi.linkedin&&<span>| {pi.linkedin}</span>}</div></div></div>
{pi.summary&&<div style={{marginBottom:sp.section}}><div style={{display:'flex',gap:'12px'}}><div style={{width:'3px',background:`linear-gradient(180deg,${color},transparent)`,borderRadius:'2px',flexShrink:0}}/><p style={{fontSize:fs.body,color:'#475569',lineHeight:1.7,margin:0}}>{pi.summary}</p></div></div>}
{data?.experience?.length>0&&<div style={{marginBottom:sp.section}}><h2 style={{fontSize:'12px',fontWeight:700,textTransform:'uppercase',letterSpacing:'3px',color,marginBottom:sp.item}}>Experience</h2>{data.experience.map((e,i)=>(<div key={i} style={{marginBottom:'16px'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'baseline'}}><div><strong style={{fontSize:fs.title}}>{e.position}</strong><span style={{fontSize:fs.body,color:'#9ca3af'}}> @ {e.company}</span></div><span style={{fontSize:'10px',color:'#9ca3af',background:'#f3f4f6',padding:'2px 8px',borderRadius:'4px'}}>{formatDate(e.startDate)}–{e.current?'Present':formatDate(e.endDate)}</span></div>{e.bullets?.filter(b=>b).map((b,bi)=>(<p key={bi} style={{fontSize:fs.body,margin:'3px 0 3px 12px',color:'#4b5563'}}>▹ {b}</p>))}</div>))}</div>}
{data?.education?.length>0&&<div style={{marginBottom:sp.section}}><h2 style={{fontSize:'12px',fontWeight:700,textTransform:'uppercase',letterSpacing:'3px',color,marginBottom:sp.item}}>Education</h2>{data.education.map((e,i)=>(<div key={i} style={{marginBottom:sp.item}}><strong style={{fontSize:fs.title}}>{e.degree} {e.field&&`in ${e.field}`}</strong><div style={{fontSize:fs.body,color:'#6b7280'}}>{e.institution}{e.gpa&&` · GPA: ${e.gpa}`}</div></div>))}</div>}
{data?.skills?.length>0&&<div style={{marginBottom:sp.section}}><h2 style={{fontSize:'12px',fontWeight:700,textTransform:'uppercase',letterSpacing:'3px',color,marginBottom:sp.item}}>Skills</h2><div style={{display:'flex',flexWrap:'wrap',gap:'6px'}}>{data.skills.map((s,i)=>(<span key={i} style={{fontSize:'10px',padding:'4px 12px',border:`1.5px solid ${color}`,borderRadius:'20px',color,fontWeight:500}}>{s.name}</span>))}</div></div>}
{data?.projects?.length>0&&<div style={{marginBottom:sp.section}}><h2 style={{fontSize:'12px',fontWeight:700,textTransform:'uppercase',letterSpacing:'3px',color,marginBottom:sp.item}}>Projects</h2>{data.projects.map((p,i)=>(<div key={i} style={{marginBottom:sp.item}}><strong style={{fontSize:fs.title}}>{p.name}</strong>{p.technologies&&<span style={{fontSize:fs.body,color:'#9ca3af'}}> | {p.technologies}</span>}{p.description&&<p style={{fontSize:fs.body,margin:'2px 0',color:'#4b5563'}}>{p.description}</p>}</div>))}</div>}
{data?.certifications?.length>0&&<div><h2 style={{fontSize:'12px',fontWeight:700,textTransform:'uppercase',letterSpacing:'3px',color,marginBottom:sp.item}}>Certifications</h2>{data.certifications.map((c,i)=>(<div key={i} style={{fontSize:fs.body,marginBottom:'3px'}}><strong>{c.name}</strong> – {c.issuer}</div>))}</div>}
</div>)};
export default T;
