import { formatDate, getFontSize, getSpacing, getSkillLevel } from './templateUtils';
const T = ({ data, theme }) => {const pi=data?.personalInfo||{};const color=theme?.primaryColor||'#818cf8';const font=theme?.fontFamily||'Inter';const fs=getFontSize(theme?.fontSize);const sp=getSpacing(theme?.spacing);return(<div style={{fontFamily:font,color:'#e2e8f0',minHeight:'1056px',background:'#0f172a'}}>
<div style={{background:'linear-gradient(135deg,#1e1b4b,#312e81)',padding:'28px 32px'}}><h1 style={{fontSize:fs.name,fontWeight:700,margin:0,color:'white'}}>{pi.fullName||'Your Name'}</h1><div style={{fontSize:fs.body,color:'#a5b4fc',marginTop:'6px',display:'flex',flexWrap:'wrap',gap:'12px'}}>{pi.email&&<span>{pi.email}</span>}{pi.phone&&<span>{pi.phone}</span>}{pi.location&&<span>{pi.location}</span>}{pi.linkedin&&<span>{pi.linkedin}</span>}</div></div>
<div style={{padding:sp.padding}}>
{pi.summary&&<div style={{marginBottom:sp.section,padding:'14px',background:'#1e293b',borderRadius:'8px',borderLeft:`3px solid ${color}`}}><p style={{fontSize:fs.body,color:'#cbd5e1',lineHeight:1.7,margin:0}}>{pi.summary}</p></div>}
{data?.experience?.length>0&&<div style={{marginBottom:sp.section}}><h2 style={{fontSize:'11px',fontWeight:700,textTransform:'uppercase',letterSpacing:'3px',color,marginBottom:sp.item}}>Experience</h2>{data.experience.map((e,i)=>(<div key={i} style={{marginBottom:'16px',padding:'12px',background:'#1e293b',borderRadius:'8px'}}><div style={{display:'flex',justifyContent:'space-between'}}><strong style={{fontSize:fs.title,color:'white'}}>{e.position}</strong><span style={{fontSize:'10px',color:'#64748b'}}>{formatDate(e.startDate)}–{e.current?'Present':formatDate(e.endDate)}</span></div><div style={{fontSize:fs.body,color}}>{e.company}</div>{e.bullets?.filter(b=>b).map((b,bi)=>(<p key={bi} style={{fontSize:fs.body,margin:'3px 0 3px 10px',color:'#94a3b8'}}>▹ {b}</p>))}</div>))}</div>}
{data?.education?.length>0&&<div style={{marginBottom:sp.section}}><h2 style={{fontSize:'11px',fontWeight:700,textTransform:'uppercase',letterSpacing:'3px',color,marginBottom:sp.item}}>Education</h2>{data.education.map((e,i)=>(<div key={i} style={{marginBottom:sp.item}}><strong style={{fontSize:fs.title,color:'white'}}>{e.degree} {e.field&&`in ${e.field}`}</strong><div style={{fontSize:fs.body,color:'#64748b'}}>{e.institution}{e.gpa&&` • GPA: ${e.gpa}`}</div></div>))}</div>}
{data?.skills?.length>0&&<div style={{marginBottom:sp.section}}><h2 style={{fontSize:'11px',fontWeight:700,textTransform:'uppercase',letterSpacing:'3px',color,marginBottom:sp.item}}>Skills</h2><div style={{display:'flex',flexWrap:'wrap',gap:'6px'}}>{data.skills.map((s,i)=>(<span key={i} style={{fontSize:'10px',padding:'4px 12px',background:'#1e293b',color,borderRadius:'6px',border:`1px solid ${color}30`,fontWeight:500}}>{s.name}</span>))}</div></div>}
{data?.projects?.length>0&&<div style={{marginBottom:sp.section}}><h2 style={{fontSize:'11px',fontWeight:700,textTransform:'uppercase',letterSpacing:'3px',color,marginBottom:sp.item}}>Projects</h2>{data.projects.map((p,i)=>(<div key={i} style={{marginBottom:sp.item,padding:'12px',background:'#1e293b',borderRadius:'8px'}}><strong style={{fontSize:fs.title,color:'white'}}>{p.name}</strong>{p.technologies&&<div style={{fontSize:'10px',color,marginTop:'2px'}}>{p.technologies}</div>}{p.description&&<p style={{fontSize:fs.body,margin:'4px 0 0',color:'#94a3b8'}}>{p.description}</p>}</div>))}</div>}
{data?.certifications?.length>0&&<div><h2 style={{fontSize:'11px',fontWeight:700,textTransform:'uppercase',letterSpacing:'3px',color,marginBottom:sp.item}}>Certifications</h2>{data.certifications.map((c,i)=>(<div key={i} style={{fontSize:fs.body,marginBottom:'4px',color:'#94a3b8'}}><strong style={{color:'white'}}>{c.name}</strong> – {c.issuer}</div>))}</div>}
</div></div>)};
export default T;
