import { formatDate, getFontSize, getSpacing, getSkillLevel } from './templateUtils';
const T = ({ data, theme }) => {const pi=data?.personalInfo||{};const color=theme?.primaryColor||'#a78bfa';const color2='#f472b6';const font=theme?.fontFamily||'Outfit';const fs=getFontSize(theme?.fontSize);const sp=getSpacing(theme?.spacing);return(<div style={{fontFamily:font,color:'#e2e8f0',minHeight:'1056px',background:'#0a0a1a',display:'flex'}}>
<div style={{width:'36%',background:'linear-gradient(180deg,#1a1a2e,#16162a)',padding:'28px 20px'}}><div style={{textAlign:'center',marginBottom:'24px'}}><div style={{width:'80px',height:'80px',borderRadius:'50%',background:`linear-gradient(135deg,${color},${color2})`,margin:'0 auto 12px',display:'flex',alignItems:'center',justifyContent:'center',fontSize:'28px',fontWeight:800,color:'white'}}>{(pi.fullName||'Y')[0]}</div><h1 style={{fontSize:'18px',fontWeight:700,margin:0,color:'white'}}>{pi.fullName||'Your Name'}</h1></div>
<div style={{fontSize:'10px',marginBottom:'20px',color:'#94a3b8',lineHeight:2}}>{pi.email&&<div>✉ {pi.email}</div>}{pi.phone&&<div>☎ {pi.phone}</div>}{pi.location&&<div>◉ {pi.location}</div>}{pi.linkedin&&<div>◈ {pi.linkedin}</div>}</div>
{data?.skills?.length>0&&<div style={{marginBottom:'20px'}}><h3 style={{fontSize:'10px',textTransform:'uppercase',letterSpacing:'2px',color,marginBottom:'10px',paddingBottom:'4px',borderBottom:`1px solid ${color}30`}}>Skills</h3>{data.skills.map((s,i)=>(<div key={i} style={{marginBottom:'6px'}}><div style={{fontSize:'10px',marginBottom:'2px',color:'#cbd5e1'}}>{s.name}</div><div style={{width:'100%',height:'3px',background:'#1e1e3a',borderRadius:'2px'}}><div style={{width:`${getSkillLevel(s.level)}%`,height:'100%',background:`linear-gradient(90deg,${color},${color2})`,borderRadius:'2px'}}/></div></div>))}</div>}
{data?.certifications?.length>0&&<div><h3 style={{fontSize:'10px',textTransform:'uppercase',letterSpacing:'2px',color,marginBottom:'10px',paddingBottom:'4px',borderBottom:`1px solid ${color}30`}}>Certs</h3>{data.certifications.map((c,i)=>(<div key={i} style={{fontSize:'10px',marginBottom:'8px',color:'#94a3b8'}}><div style={{fontWeight:600,color:'#cbd5e1'}}>{c.name}</div><div>{c.issuer}</div></div>))}</div>}
</div>
<div style={{flex:1,padding:sp.padding}}>
{pi.summary&&<div style={{marginBottom:sp.section}}><h2 style={{fontSize:'11px',fontWeight:700,textTransform:'uppercase',letterSpacing:'2px',color,marginBottom:'8px'}}>About</h2><p style={{fontSize:fs.body,color:'#94a3b8',lineHeight:1.7}}>{pi.summary}</p></div>}
{data?.experience?.length>0&&<div style={{marginBottom:sp.section}}><h2 style={{fontSize:'11px',fontWeight:700,textTransform:'uppercase',letterSpacing:'2px',color,marginBottom:'8px'}}>Experience</h2>{data.experience.map((e,i)=>(<div key={i} style={{marginBottom:'14px',paddingLeft:'14px',borderLeft:`2px solid ${i%2===0?color:color2}`}}><div style={{display:'flex',justifyContent:'space-between'}}><strong style={{fontSize:fs.title,color:'white'}}>{e.position}</strong><span style={{fontSize:'10px',color:'#64748b'}}>{formatDate(e.startDate)}–{e.current?'Present':formatDate(e.endDate)}</span></div><div style={{fontSize:fs.body,color:i%2===0?color:color2}}>{e.company}</div>{e.bullets?.filter(b=>b).map((b,bi)=>(<p key={bi} style={{fontSize:fs.body,margin:'3px 0',color:'#94a3b8'}}>• {b}</p>))}</div>))}</div>}
{data?.education?.length>0&&<div style={{marginBottom:sp.section}}><h2 style={{fontSize:'11px',fontWeight:700,textTransform:'uppercase',letterSpacing:'2px',color,marginBottom:'8px'}}>Education</h2>{data.education.map((e,i)=>(<div key={i} style={{marginBottom:sp.item}}><strong style={{fontSize:fs.title,color:'white'}}>{e.degree} {e.field&&`in ${e.field}`}</strong><div style={{fontSize:fs.body,color:'#64748b'}}>{e.institution}{e.gpa&&` • GPA: ${e.gpa}`}</div></div>))}</div>}
{data?.projects?.length>0&&<div><h2 style={{fontSize:'11px',fontWeight:700,textTransform:'uppercase',letterSpacing:'2px',color,marginBottom:'8px'}}>Projects</h2>{data.projects.map((p,i)=>(<div key={i} style={{marginBottom:sp.item,padding:'10px',background:'#1a1a2e',borderRadius:'6px'}}><strong style={{fontSize:fs.title,color:'white'}}>{p.name}</strong>{p.technologies&&<div style={{fontSize:'10px',color:color2,marginTop:'2px'}}>{p.technologies}</div>}{p.description&&<p style={{fontSize:fs.body,margin:'4px 0 0',color:'#94a3b8'}}>{p.description}</p>}</div>))}</div>}
</div></div>)};
export default T;
