import { formatDate, getFontSize, getSpacing } from './templateUtils';
const MinimalSleek = ({ data, theme }) => {
  const pi = data?.personalInfo || {};const color = theme?.primaryColor || '#06b6d4';const font = theme?.fontFamily || 'Inter';const fs = getFontSize(theme?.fontSize);const sp = getSpacing(theme?.spacing);
  return (<div style={{ fontFamily: font, color: '#0f172a', padding: sp.padding, background: 'white', minHeight: '1056px' }}>
    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: sp.section, paddingBottom: '12px', borderBottom: '2px solid #0f172a' }}>
      <h1 style={{ fontSize: fs.name, fontWeight: 800, margin: 0 }}>{pi.fullName || 'Your Name'}</h1>
      <div style={{ textAlign: 'right', fontSize: fs.body, color: '#64748b' }}>{pi.email && <div>{pi.email}</div>}{pi.phone && <div>{pi.phone}</div>}{pi.location && <div>{pi.location}</div>}</div>
    </div>
    {pi.summary && <p style={{ fontSize: fs.body, color: '#475569', marginBottom: sp.section, lineHeight: 1.6 }}>{pi.summary}</p>}
    {data?.experience?.length > 0 && <div style={{ marginBottom: sp.section }}><h2 style={{ fontSize: '11px', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '3px', color, marginBottom: sp.item }}>Experience</h2>{data.experience.map((exp, i) => (<div key={i} style={{ marginBottom: '14px' }}><div style={{ display: 'flex', justifyContent: 'space-between' }}><div><strong style={{ fontSize: fs.title }}>{exp.position}</strong><span style={{ color: '#94a3b8' }}> at {exp.company}</span></div><span style={{ fontSize: fs.body, color: '#94a3b8' }}>{formatDate(exp.startDate)} – {exp.current ? 'Present' : formatDate(exp.endDate)}</span></div>{exp.bullets?.filter(b => b).map((b, bi) => (<p key={bi} style={{ fontSize: fs.body, color: '#475569', margin: '3px 0 3px 12px' }}>▸ {b}</p>))}</div>))}</div>}
    {data?.education?.length > 0 && <div style={{ marginBottom: sp.section }}><h2 style={{ fontSize: '11px', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '3px', color, marginBottom: sp.item }}>Education</h2>{data.education.map((edu, i) => (<div key={i} style={{ marginBottom: sp.item, display: 'flex', justifyContent: 'space-between' }}><div><strong style={{ fontSize: fs.title }}>{edu.degree} {edu.field && `– ${edu.field}`}</strong><div style={{ fontSize: fs.body, color: '#64748b' }}>{edu.institution}{edu.gpa && ` | GPA: ${edu.gpa}`}</div></div><span style={{ fontSize: fs.body, color: '#94a3b8' }}>{formatDate(edu.endDate)}</span></div>))}</div>}
    {data?.skills?.length > 0 && <div style={{ marginBottom: sp.section }}><h2 style={{ fontSize: '11px', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '3px', color, marginBottom: sp.item }}>Skills</h2><div style={{ display: 'flex', flexWrap: 'wrap', gap: '4px' }}>{data.skills.map((s, i) => (<span key={i} style={{ fontSize: '10px', padding: '3px 10px', border: `1px solid ${color}40`, borderRadius: '3px', color: '#334155' }}>{s.name}</span>))}</div></div>}
    {data?.projects?.length > 0 && <div style={{ marginBottom: sp.section }}><h2 style={{ fontSize: '11px', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '3px', color, marginBottom: sp.item }}>Projects</h2>{data.projects.map((p, i) => (<div key={i} style={{ marginBottom: sp.item }}><strong style={{ fontSize: fs.title }}>{p.name}</strong>{p.technologies && <span style={{ fontSize: fs.body, color: '#94a3b8' }}> | {p.technologies}</span>}{p.description && <p style={{ fontSize: fs.body, color: '#475569', margin: '2px 0' }}>{p.description}</p>}</div>))}</div>}
    {data?.certifications?.length > 0 && <div><h2 style={{ fontSize: '11px', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '3px', color, marginBottom: sp.item }}>Certifications</h2>{data.certifications.map((c, i) => (<div key={i} style={{ fontSize: fs.body, marginBottom: '2px' }}>{c.name} – {c.issuer}</div>))}</div>}
  </div>);
};
export default MinimalSleek;
