import { formatDate, getFontSize, getSpacing } from './templateUtils';
const MinimalFresh = ({ data, theme }) => {
  const pi = data?.personalInfo || {};const color = theme?.primaryColor || '#10b981';const font = theme?.fontFamily || 'Poppins';const fs = getFontSize(theme?.fontSize);const sp = getSpacing(theme?.spacing);
  return (<div style={{ fontFamily: font, color: '#1f2937', padding: sp.padding, background: 'white', minHeight: '1056px' }}>
    <div style={{ background: `linear-gradient(135deg, ${color}15, ${color}05)`, padding: '24px', borderRadius: '12px', marginBottom: sp.section }}>
      <h1 style={{ fontSize: fs.name, fontWeight: 700, color: '#111', margin: 0 }}>{pi.fullName || 'Your Name'}</h1>
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: '10px', marginTop: '8px', fontSize: fs.body, color: '#6b7280' }}>{pi.email && <span>📧 {pi.email}</span>}{pi.phone && <span>📱 {pi.phone}</span>}{pi.location && <span>📍 {pi.location}</span>}</div>
      {pi.summary && <p style={{ fontSize: fs.body, color: '#374151', marginTop: '12px', lineHeight: 1.6 }}>{pi.summary}</p>}
    </div>
    {data?.experience?.length > 0 && <div style={{ marginBottom: sp.section }}><h2 style={{ fontSize: fs.section, fontWeight: 700, color, marginBottom: sp.item, display: 'flex', alignItems: 'center', gap: '8px' }}><span style={{ width: '20px', height: '3px', background: color, display: 'inline-block' }} /> Experience</h2>{data.experience.map((exp, i) => (<div key={i} style={{ marginBottom: '14px', paddingLeft: '28px' }}><div style={{ display: 'flex', justifyContent: 'space-between' }}><strong style={{ fontSize: fs.title }}>{exp.position}</strong><span style={{ fontSize: fs.body, color: '#9ca3af', background: '#f3f4f6', padding: '1px 8px', borderRadius: '4px' }}>{formatDate(exp.startDate)} – {exp.current ? 'Present' : formatDate(exp.endDate)}</span></div><div style={{ fontSize: fs.body, color, fontWeight: 500 }}>{exp.company}</div>{exp.bullets?.filter(b => b).map((b, bi) => (<p key={bi} style={{ fontSize: fs.body, color: '#4b5563', margin: '3px 0' }}>• {b}</p>))}</div>))}</div>}
    {data?.education?.length > 0 && <div style={{ marginBottom: sp.section }}><h2 style={{ fontSize: fs.section, fontWeight: 700, color, marginBottom: sp.item, display: 'flex', alignItems: 'center', gap: '8px' }}><span style={{ width: '20px', height: '3px', background: color, display: 'inline-block' }} /> Education</h2>{data.education.map((edu, i) => (<div key={i} style={{ marginBottom: sp.item, paddingLeft: '28px' }}><strong style={{ fontSize: fs.title }}>{edu.degree} {edu.field && `in ${edu.field}`}</strong><div style={{ fontSize: fs.body, color }}>{edu.institution}{edu.gpa && ` • GPA: ${edu.gpa}`}</div></div>))}</div>}
    {data?.skills?.length > 0 && <div style={{ marginBottom: sp.section }}><h2 style={{ fontSize: fs.section, fontWeight: 700, color, marginBottom: sp.item, display: 'flex', alignItems: 'center', gap: '8px' }}><span style={{ width: '20px', height: '3px', background: color, display: 'inline-block' }} /> Skills</h2><div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px', paddingLeft: '28px' }}>{data.skills.map((s, i) => (<span key={i} style={{ fontSize: '11px', padding: '4px 12px', borderRadius: '20px', background: `${color}15`, color, fontWeight: 500 }}>{s.name}</span>))}</div></div>}
    {data?.projects?.length > 0 && <div style={{ marginBottom: sp.section }}><h2 style={{ fontSize: fs.section, fontWeight: 700, color, marginBottom: sp.item, display: 'flex', alignItems: 'center', gap: '8px' }}><span style={{ width: '20px', height: '3px', background: color, display: 'inline-block' }} /> Projects</h2>{data.projects.map((p, i) => (<div key={i} style={{ marginBottom: sp.item, paddingLeft: '28px' }}><strong style={{ fontSize: fs.title }}>{p.name}</strong>{p.technologies && <span style={{ fontSize: fs.body, color: '#9ca3af' }}> | {p.technologies}</span>}{p.description && <p style={{ fontSize: fs.body, color: '#4b5563', margin: '2px 0' }}>{p.description}</p>}</div>))}</div>}
    {data?.certifications?.length > 0 && <div><h2 style={{ fontSize: fs.section, fontWeight: 700, color, marginBottom: sp.item, display: 'flex', alignItems: 'center', gap: '8px' }}><span style={{ width: '20px', height: '3px', background: color, display: 'inline-block' }} /> Certifications</h2>{data.certifications.map((c, i) => (<div key={i} style={{ fontSize: fs.body, marginBottom: '3px', paddingLeft: '28px' }}><strong>{c.name}</strong> – {c.issuer}</div>))}</div>}
  </div>);
};
export default MinimalFresh;
