import { formatDate, getFontSize, getSpacing } from './templateUtils';
const T = ({ data, theme }) => {
  const pi = data?.personalInfo || {};const color = theme?.primaryColor || '#dc2626';const font = theme?.fontFamily || 'Outfit';const fs = getFontSize(theme?.fontSize);const sp = getSpacing(theme?.spacing);
  return (<div style={{ fontFamily: font, color: '#111', padding: sp.padding, background: 'white', minHeight: '1056px' }}>
    <div style={{ marginBottom: sp.section }}><h1 style={{ fontSize: '32px', fontWeight: 900, margin: 0, lineHeight: 1.1 }}>{pi.fullName || 'YOUR NAME'}</h1><div style={{ width: '100%', height: '6px', background: `linear-gradient(90deg, ${color}, ${color}00)`, marginTop: '8px', borderRadius: '3px' }} /><div style={{ fontSize: fs.body, color: '#6b7280', marginTop: '8px', display: 'flex', flexWrap: 'wrap', gap: '10px' }}>{pi.email && <span>{pi.email}</span>}{pi.phone && <span>| {pi.phone}</span>}{pi.location && <span>| {pi.location}</span>}</div></div>
    {pi.summary && <div style={{ marginBottom: sp.section, background: `${color}08`, padding: '14px', borderRadius: '8px' }}><p style={{ fontSize: fs.body, lineHeight: 1.6, margin: 0 }}>{pi.summary}</p></div>}
    {data?.experience?.length > 0 && <div style={{ marginBottom: sp.section }}><h2 style={{ fontSize: fs.section, fontWeight: 800, color, marginBottom: sp.item }}>EXPERIENCE</h2>{data.experience.map((exp, i) => (<div key={i} style={{ marginBottom: '14px' }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline' }}><strong style={{ fontSize: fs.title }}>{exp.position}</strong><span style={{ fontSize: '10px', fontWeight: 700, color }}>{formatDate(exp.startDate)} – {exp.current ? 'NOW' : formatDate(exp.endDate)}</span></div><div style={{ fontSize: fs.body, color: '#4b5563', fontWeight: 600 }}>{exp.company}</div>{exp.bullets?.filter(b => b).map((b, bi) => (<p key={bi} style={{ fontSize: fs.body, margin: '3px 0 3px 10px', color: '#374151' }}>▪ {b}</p>))}</div>))}</div>}
    {data?.education?.length > 0 && <div style={{ marginBottom: sp.section }}><h2 style={{ fontSize: fs.section, fontWeight: 800, color, marginBottom: sp.item }}>EDUCATION</h2>{data.education.map((edu, i) => (<div key={i} style={{ marginBottom: sp.item }}><strong style={{ fontSize: fs.title }}>{edu.degree} {edu.field && `— ${edu.field}`}</strong><div style={{ fontSize: fs.body, color: '#4b5563' }}>{edu.institution}{edu.gpa && ` | GPA: ${edu.gpa}`}</div></div>))}</div>}
    {data?.skills?.length > 0 && <div style={{ marginBottom: sp.section }}><h2 style={{ fontSize: fs.section, fontWeight: 800, color, marginBottom: sp.item }}>SKILLS</h2><div style={{ display: 'flex', flexWrap: 'wrap', gap: '5px' }}>{data.skills.map((s, i) => (<span key={i} style={{ fontSize: '11px', padding: '4px 12px', background: `${color}12`, color, borderRadius: '4px', fontWeight: 600 }}>{s.name}</span>))}</div></div>}
    {data?.projects?.length > 0 && <div style={{ marginBottom: sp.section }}><h2 style={{ fontSize: fs.section, fontWeight: 800, color, marginBottom: sp.item }}>PROJECTS</h2>{data.projects.map((p, i) => (<div key={i} style={{ marginBottom: sp.item }}><strong style={{ fontSize: fs.title }}>{p.name}</strong>{p.technologies && <span style={{ fontSize: fs.body, color: '#9ca3af' }}> | {p.technologies}</span>}{p.description && <p style={{ fontSize: fs.body, margin: '2px 0' }}>{p.description}</p>}</div>))}</div>}
    {data?.certifications?.length > 0 && <div><h2 style={{ fontSize: fs.section, fontWeight: 800, color, marginBottom: sp.item }}>CERTIFICATIONS</h2>{data.certifications.map((c, i) => (<div key={i} style={{ fontSize: fs.body, marginBottom: '3px' }}><strong>{c.name}</strong> – {c.issuer}</div>))}</div>}
  </div>);
};
export default T;
