import { formatDate, getFontSize, getSpacing, getSkillLevel } from './templateUtils';
const T = ({ data, theme }) => {
  const pi = data?.personalInfo || {};const color = theme?.primaryColor || '#0f172a';const font = theme?.fontFamily || 'Inter';const fs = getFontSize(theme?.fontSize);const sp = getSpacing(theme?.spacing);
  return (<div style={{ fontFamily: font, display: 'flex', minHeight: '1056px', background: 'white' }}>
    {/* Sidebar */}
    <div style={{ width: '35%', background: color, color: 'white', padding: '28px 20px' }}>
      <div style={{ textAlign: 'center', marginBottom: '24px' }}>
        <div style={{ width: '80px', height: '80px', borderRadius: '50%', background: 'rgba(255,255,255,0.15)', margin: '0 auto 12px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '28px', fontWeight: 700 }}>{(pi.fullName || 'Y')[0]}</div>
        <h1 style={{ fontSize: '18px', fontWeight: 700, margin: 0 }}>{pi.fullName || 'Your Name'}</h1>
      </div>
      <div style={{ fontSize: '10px', marginBottom: '20px', opacity: 0.85, lineHeight: 1.8 }}>{pi.email && <div>✉ {pi.email}</div>}{pi.phone && <div>☎ {pi.phone}</div>}{pi.location && <div>◉ {pi.location}</div>}{pi.linkedin && <div>◈ {pi.linkedin}</div>}{pi.website && <div>◇ {pi.website}</div>}</div>
      {data?.skills?.length > 0 && <div style={{ marginBottom: '20px' }}><h3 style={{ fontSize: '11px', textTransform: 'uppercase', letterSpacing: '2px', marginBottom: '10px', borderBottom: '1px solid rgba(255,255,255,0.2)', paddingBottom: '4px' }}>Skills</h3>{data.skills.map((s, i) => (<div key={i} style={{ marginBottom: '6px' }}><div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '10px', marginBottom: '2px' }}><span>{s.name}</span><span style={{ opacity: 0.6 }}>{s.level}</span></div><div style={{ width: '100%', height: '3px', background: 'rgba(255,255,255,0.15)', borderRadius: '2px' }}><div style={{ width: `${getSkillLevel(s.level)}%`, height: '100%', background: 'rgba(255,255,255,0.7)', borderRadius: '2px' }} /></div></div>))}</div>}
      {data?.certifications?.length > 0 && <div><h3 style={{ fontSize: '11px', textTransform: 'uppercase', letterSpacing: '2px', marginBottom: '10px', borderBottom: '1px solid rgba(255,255,255,0.2)', paddingBottom: '4px' }}>Certifications</h3>{data.certifications.map((c, i) => (<div key={i} style={{ fontSize: '10px', marginBottom: '8px' }}><div style={{ fontWeight: 600 }}>{c.name}</div><div style={{ opacity: 0.7 }}>{c.issuer}</div></div>))}</div>}
    </div>
    {/* Main content */}
    <div style={{ flex: 1, padding: sp.padding }}>
      {pi.summary && <div style={{ marginBottom: sp.section }}><h2 style={{ fontSize: '11px', fontWeight: 700, textTransform: 'uppercase', color, letterSpacing: '2px', marginBottom: '8px', borderBottom: `2px solid ${color}`, paddingBottom: '4px' }}>Profile</h2><p style={{ fontSize: fs.body, color: '#475569', lineHeight: 1.6 }}>{pi.summary}</p></div>}
      {data?.experience?.length > 0 && <div style={{ marginBottom: sp.section }}><h2 style={{ fontSize: '11px', fontWeight: 700, textTransform: 'uppercase', color, letterSpacing: '2px', marginBottom: '8px', borderBottom: `2px solid ${color}`, paddingBottom: '4px' }}>Experience</h2>{data.experience.map((exp, i) => (<div key={i} style={{ marginBottom: '14px' }}><div style={{ display: 'flex', justifyContent: 'space-between' }}><strong style={{ fontSize: fs.title }}>{exp.position}</strong><span style={{ fontSize: '10px', color: '#9ca3af' }}>{formatDate(exp.startDate)} – {exp.current ? 'Present' : formatDate(exp.endDate)}</span></div><div style={{ fontSize: fs.body, color, fontWeight: 500 }}>{exp.company}</div>{exp.bullets?.filter(b => b).map((b, bi) => (<p key={bi} style={{ fontSize: fs.body, color: '#4b5563', margin: '3px 0 3px 10px' }}>• {b}</p>))}</div>))}</div>}
      {data?.education?.length > 0 && <div style={{ marginBottom: sp.section }}><h2 style={{ fontSize: '11px', fontWeight: 700, textTransform: 'uppercase', color, letterSpacing: '2px', marginBottom: '8px', borderBottom: `2px solid ${color}`, paddingBottom: '4px' }}>Education</h2>{data.education.map((edu, i) => (<div key={i} style={{ marginBottom: sp.item }}><strong style={{ fontSize: fs.title }}>{edu.degree} {edu.field && `in ${edu.field}`}</strong><div style={{ fontSize: fs.body, color: '#6b7280' }}>{edu.institution}{edu.gpa && ` • GPA: ${edu.gpa}`}</div></div>))}</div>}
      {data?.projects?.length > 0 && <div><h2 style={{ fontSize: '11px', fontWeight: 700, textTransform: 'uppercase', color, letterSpacing: '2px', marginBottom: '8px', borderBottom: `2px solid ${color}`, paddingBottom: '4px' }}>Projects</h2>{data.projects.map((p, i) => (<div key={i} style={{ marginBottom: sp.item }}><strong style={{ fontSize: fs.title }}>{p.name}</strong>{p.technologies && <span style={{ fontSize: fs.body, color: '#9ca3af' }}> | {p.technologies}</span>}{p.description && <p style={{ fontSize: fs.body, margin: '2px 0' }}>{p.description}</p>}</div>))}</div>}
    </div>
  </div>);
};
export default T;
