import { formatDate, getFontSize, getSpacing } from './templateUtils';
const T = ({ data, theme }) => {
  const pi = data?.personalInfo || {};const color = theme?.primaryColor || '#2563eb';const font = theme?.fontFamily || 'Roboto';const fs = getFontSize(theme?.fontSize);const sp = getSpacing(theme?.spacing);
  return (<div style={{ fontFamily: font, color: '#1f2937', background: 'white', minHeight: '1056px' }}>
    <div style={{ background: color, color: 'white', padding: '28px 32px' }}>
      <h1 style={{ fontSize: fs.name, fontWeight: 700, margin: 0 }}>{pi.fullName || 'Your Name'}</h1>
      <div style={{ fontSize: fs.body, opacity: 0.9, marginTop: '6px', display: 'flex', flexWrap: 'wrap', gap: '12px' }}>{pi.email && <span>✉ {pi.email}</span>}{pi.phone && <span>☎ {pi.phone}</span>}{pi.location && <span>◉ {pi.location}</span>}{pi.linkedin && <span>◈ {pi.linkedin}</span>}</div>
    </div>
    <div style={{ padding: sp.padding }}>
      {pi.summary && <div style={{ marginBottom: sp.section, borderLeft: `4px solid ${color}`, paddingLeft: '16px' }}><h2 style={{ fontSize: '11px', fontWeight: 700, textTransform: 'uppercase', color, marginBottom: '6px', letterSpacing: '1px' }}>About</h2><p style={{ fontSize: fs.body, lineHeight: 1.6 }}>{pi.summary}</p></div>}
      {data?.experience?.length > 0 && <div style={{ marginBottom: sp.section }}><h2 style={{ fontSize: '11px', fontWeight: 700, textTransform: 'uppercase', color, marginBottom: sp.item, letterSpacing: '1px', borderBottom: `2px solid ${color}`, paddingBottom: '4px' }}>Professional Experience</h2>{data.experience.map((exp, i) => (<div key={i} style={{ marginBottom: '16px' }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline' }}><strong style={{ fontSize: fs.title }}>{exp.position}</strong><span style={{ fontSize: '10px', color: 'white', background: color, padding: '2px 8px', borderRadius: '3px' }}>{formatDate(exp.startDate)} – {exp.current ? 'Present' : formatDate(exp.endDate)}</span></div><div style={{ fontSize: fs.body, color, fontWeight: 500 }}>{exp.company}</div>{exp.bullets?.filter(b => b).map((b, bi) => (<p key={bi} style={{ fontSize: fs.body, margin: '3px 0 3px 12px', color: '#4b5563' }}>• {b}</p>))}</div>))}</div>}
      {data?.education?.length > 0 && <div style={{ marginBottom: sp.section }}><h2 style={{ fontSize: '11px', fontWeight: 700, textTransform: 'uppercase', color, marginBottom: sp.item, letterSpacing: '1px', borderBottom: `2px solid ${color}`, paddingBottom: '4px' }}>Education</h2>{data.education.map((edu, i) => (<div key={i} style={{ marginBottom: sp.item }}><strong style={{ fontSize: fs.title }}>{edu.degree} {edu.field && `in ${edu.field}`}</strong><div style={{ fontSize: fs.body, color }}>{edu.institution}{edu.gpa && ` | GPA: ${edu.gpa}`}</div><div style={{ fontSize: fs.body, color: '#9ca3af' }}>{formatDate(edu.startDate)} – {formatDate(edu.endDate)}</div></div>))}</div>}
      {data?.skills?.length > 0 && <div style={{ marginBottom: sp.section }}><h2 style={{ fontSize: '11px', fontWeight: 700, textTransform: 'uppercase', color, marginBottom: sp.item, letterSpacing: '1px', borderBottom: `2px solid ${color}`, paddingBottom: '4px' }}>Skills</h2><div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px' }}>{data.skills.map((s, i) => (<span key={i} style={{ fontSize: '10px', padding: '4px 12px', background: `${color}10`, color, borderRadius: '4px', fontWeight: 500 }}>{s.name}</span>))}</div></div>}
      {data?.projects?.length > 0 && <div style={{ marginBottom: sp.section }}><h2 style={{ fontSize: '11px', fontWeight: 700, textTransform: 'uppercase', color, marginBottom: sp.item, letterSpacing: '1px', borderBottom: `2px solid ${color}`, paddingBottom: '4px' }}>Projects</h2>{data.projects.map((p, i) => (<div key={i} style={{ marginBottom: sp.item }}><strong style={{ fontSize: fs.title }}>{p.name}</strong>{p.technologies && <span style={{ fontSize: fs.body, color: '#9ca3af' }}> | {p.technologies}</span>}{p.description && <p style={{ fontSize: fs.body, margin: '2px 0' }}>{p.description}</p>}</div>))}</div>}
      {data?.certifications?.length > 0 && <div><h2 style={{ fontSize: '11px', fontWeight: 700, textTransform: 'uppercase', color, marginBottom: sp.item, letterSpacing: '1px', borderBottom: `2px solid ${color}`, paddingBottom: '4px' }}>Certifications</h2>{data.certifications.map((c, i) => (<div key={i} style={{ fontSize: fs.body, marginBottom: '3px' }}><strong>{c.name}</strong> — {c.issuer}</div>))}</div>}
    </div>
  </div>);
};
export default T;
