import { formatDate, getFontSize, getSpacing } from './templateUtils';
const T = ({ data, theme }) => {
  const pi = data?.personalInfo || {};const color = theme?.primaryColor || '#7c3aed';const font = theme?.fontFamily || 'Inter';const fs = getFontSize(theme?.fontSize);const sp = getSpacing(theme?.spacing);
  return (<div style={{ fontFamily: font, color: '#1f2937', padding: sp.padding, background: 'white', minHeight: '1056px' }}>
    <div style={{ textAlign: 'center', marginBottom: sp.section }}><h1 style={{ fontSize: fs.name, fontWeight: 700, margin: 0 }}>{pi.fullName || 'Your Name'}</h1><div style={{ fontSize: fs.body, color: '#6b7280', marginTop: '6px' }}>{[pi.email, pi.phone, pi.location].filter(Boolean).join(' • ')}</div></div>
    {pi.summary && <div style={{ marginBottom: sp.section }}><p style={{ fontSize: fs.body, color: '#475569', lineHeight: 1.6, borderLeft: `3px solid ${color}`, paddingLeft: '12px' }}>{pi.summary}</p></div>}
    {data?.experience?.length > 0 && <div style={{ marginBottom: sp.section }}><h2 style={{ fontSize: fs.section, fontWeight: 700, color, marginBottom: sp.item }}>Experience</h2>{data.experience.map((exp, i) => (<div key={i} style={{ marginBottom: '16px', display: 'flex', gap: '16px' }}><div style={{ flexShrink: 0, width: '80px', textAlign: 'right', fontSize: '10px', color: '#9ca3af', paddingTop: '3px' }}>{formatDate(exp.startDate)}<br />{exp.current ? 'Present' : formatDate(exp.endDate)}</div><div style={{ position: 'relative', paddingLeft: '20px', borderLeft: `2px solid ${color}30` }}><div style={{ position: 'absolute', left: '-6px', top: '4px', width: '10px', height: '10px', borderRadius: '50%', background: color }} /><strong style={{ fontSize: fs.title }}>{exp.position}</strong><div style={{ fontSize: fs.body, color }}>{exp.company}</div>{exp.bullets?.filter(b => b).map((b, bi) => (<p key={bi} style={{ fontSize: fs.body, color: '#4b5563', margin: '3px 0' }}>• {b}</p>))}</div></div>))}</div>}
    {data?.education?.length > 0 && <div style={{ marginBottom: sp.section }}><h2 style={{ fontSize: fs.section, fontWeight: 700, color, marginBottom: sp.item }}>Education</h2>{data.education.map((edu, i) => (<div key={i} style={{ marginBottom: sp.item, display: 'flex', gap: '16px' }}><div style={{ flexShrink: 0, width: '80px', textAlign: 'right', fontSize: '10px', color: '#9ca3af' }}>{formatDate(edu.endDate)}</div><div style={{ paddingLeft: '20px', borderLeft: `2px solid ${color}30`, position: 'relative' }}><div style={{ position: 'absolute', left: '-6px', top: '4px', width: '10px', height: '10px', borderRadius: '50%', background: `${color}60` }} /><strong style={{ fontSize: fs.title }}>{edu.degree} {edu.field && `in ${edu.field}`}</strong><div style={{ fontSize: fs.body, color: '#6b7280' }}>{edu.institution}{edu.gpa && ` • GPA: ${edu.gpa}`}</div></div></div>))}</div>}
    {data?.skills?.length > 0 && <div style={{ marginBottom: sp.section }}><h2 style={{ fontSize: fs.section, fontWeight: 700, color, marginBottom: sp.item }}>Skills</h2><div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px' }}>{data.skills.map((s, i) => (<span key={i} style={{ fontSize: '10px', padding: '3px 10px', background: `${color}10`, color, borderRadius: '4px', fontWeight: 500 }}>{s.name}</span>))}</div></div>}
    {data?.projects?.length > 0 && <div style={{ marginBottom: sp.section }}><h2 style={{ fontSize: fs.section, fontWeight: 700, color, marginBottom: sp.item }}>Projects</h2>{data.projects.map((p, i) => (<div key={i} style={{ marginBottom: sp.item }}><strong style={{ fontSize: fs.title }}>{p.name}</strong>{p.technologies && <span style={{ fontSize: fs.body, color: '#9ca3af' }}> | {p.technologies}</span>}{p.description && <p style={{ fontSize: fs.body, margin: '2px 0' }}>{p.description}</p>}</div>))}</div>}
    {data?.certifications?.length > 0 && <div><h2 style={{ fontSize: fs.section, fontWeight: 700, color, marginBottom: sp.item }}>Certifications</h2>{data.certifications.map((c, i) => (<div key={i} style={{ fontSize: fs.body, marginBottom: '3px' }}><strong>{c.name}</strong> – {c.issuer}</div>))}</div>}
  </div>);
};
export default T;
